// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using crm.webapi.Data;

#nullable disable

namespace crm.webapi.Migrations
{
    [DbContext(typeof(CrmContext))]
    [Migration("20240117152849_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("crm.webapi.Models.Banco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Complemento")
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fantasia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Razao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("telefone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tb_Bancos", (string)null);
                });

            modelBuilder.Entity("crm.webapi.Models.Clausula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Desc_Clausula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tb_Clausulas", (string)null);
                });

            modelBuilder.Entity("crm.webapi.Models.Clausula_Abusiva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_Contrato")
                        .HasColumnType("integer");

                    b.Property<int>("Id_clausula")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor_Clausula")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Tb_Clausulas_Abusivas", (string)null);
                });

            modelBuilder.Entity("crm.webapi.Models.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cet_Anual")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Cet_Mensal")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Dt_Ins")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Dt_Upd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Banco")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Pessoa")
                        .HasColumnType("integer");

                    b.Property<decimal>("Iof")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Juros_Anual")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Juros_Mensal")
                        .HasColumnType("numeric");

                    b.Property<string>("Num_Contrato")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Parcelas")
                        .HasColumnType("integer");

                    b.Property<decimal>("Saldo_Financiar")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Taxa_Media_Juros")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total_Acao")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total_Clausulas_Abusivas_Iof")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total_Financiamento")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Valor_Bem")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Valor_Entrada")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Valor_Financiar")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Valor_Parcela")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Valor_Tutela")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Tb_Contratos", (string)null);
                });

            modelBuilder.Entity("crm.webapi.Models.Endereco", b =>
                {
                    b.Property<string>("Cep")
                        .HasColumnType("text");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Cep");

                    b.ToTable("Tb_Enderecos", (string)null);
                });

            modelBuilder.Entity("crm.webapi.Models.Estado_Civil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tb_Estado_Civil", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "Solteiro"
                        },
                        new
                        {
                            Id = 2,
                            Estado = "Casado"
                        },
                        new
                        {
                            Id = 3,
                            Estado = "Divorciado"
                        },
                        new
                        {
                            Id = 4,
                            Estado = "Viúvo"
                        },
                        new
                        {
                            Id = 5,
                            Estado = "União Estavel"
                        });
                });

            modelBuilder.Entity("crm.webapi.Models.Forum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .HasColumnType("text");

                    b.Property<string>("Foro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tb_Foruns", (string)null);
                });

            modelBuilder.Entity("crm.webapi.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .HasColumnType("text");

                    b.Property<string>("Cep")
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .HasColumnType("text");

                    b.Property<string>("Complemento")
                        .HasColumnType("text");

                    b.Property<string>("Cpf")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int?>("Estado_CivilId")
                        .HasColumnType("integer");

                    b.Property<string>("Exp")
                        .HasColumnType("text");

                    b.Property<string>("Logradouro")
                        .HasColumnType("text");

                    b.Property<string>("Nacionalidade")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .HasColumnType("text");

                    b.Property<string>("Profissao")
                        .HasColumnType("text");

                    b.Property<string>("Rg")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<string>("Uf")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Estado_CivilId");

                    b.ToTable("Tb_Pessoas", (string)null);
                });

            modelBuilder.Entity("crm.webapi.Models.Processo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comarca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Forum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id_Contrato")
                        .HasColumnType("integer");

                    b.Property<bool>("Justica_Gratuita")
                        .HasColumnType("boolean");

                    b.Property<string>("Numero_Processo")
                        .HasColumnType("text");

                    b.Property<string>("Status_Financiamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tb_Processos", (string)null);
                });

            modelBuilder.Entity("crm.webapi.Models.Pessoa", b =>
                {
                    b.HasOne("crm.webapi.Models.Estado_Civil", "Estado_Civil")
                        .WithMany()
                        .HasForeignKey("Estado_CivilId");

                    b.Navigation("Estado_Civil");
                });
#pragma warning restore 612, 618
        }
    }
}
